#!/bin/sh

# Loop one segment repeatedly
# given an argument, find the matching segment to loop
# otherwise loop the first segment

file=`scripts/show-marks`

# check for a search string or use the first two marks in the file
[[ ! -z $@ ]] && match=$(grep -A1 "$@" "$file")
[[ $? -eq 1 ]] && match=$(cat "$file")

a=$(echo "$match" | head -1 | cut -d' ' -f1)
b=$(echo "$match" | head -2 | tail -1 | cut -d' ' -f1)
loopDuration=`expr $b - $a`

loop() {
  (echo "player-pause"; echo "seek $a"; echo "player-play") | cmus-remote
  sleep $loopDuration
  ./scripts/sleep-until-play-resumes
  loop
}

loop
