#!/bin/sh

track="$(cmus-remote -Q \
  | grep '^file' \
  | sed 's/file //; s|/Users/kjell/||; s|\..*$||')"
file="$HOME/.config/cmus/marks/$track"

a=$(cat "$file" | head -1)
b=$(cat "$file" | head -2 | tail -1)
loopDuration=`expr $b - $a`

loop() {
  (echo "player-pause"; echo "seek $a"; echo "player-play") | cmus-remote
  sleep $loopDuration
  playingStatus=$(cmus-remote -Q | grep '^status' | cut -d' ' -f2)
  [ $playingStatus == 'playing' ] && loop
}

loop
