#!/bin/sh
#
# TODO: find the closest mark and skip to the next
# or skip to a mark by searching the name


file=`scripts/show-marks`
position=`grep "$@" "$file" | cut -d ' ' -f1`

[[ ! -z $position ]] && echo "seek $position" | cmus-remote
